baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  author = "Jeremie Sophikitis"
  avatar = "profile.png"
  email = "jeremie.soffichiti@gmail.com"
  email_full = "mailto:youremail@me.com"
  website = "git.io/sustain"
  website_full = "https://demo.nurlan.co/hugo-sustain/"
  github = "trending"
  twitter = "twitter"
  tel = "+33 6 77 89 63 49"
  tel_full = "+33677896349"
  google_maps = "https://www.google.co.uk/maps/place/Lyon"
  address = "44 Perth Street"
  postcode = "EH3 5BL"
  city = "Lyon"
  country = "France"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Djordje Atlialp"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Hello Friend NG"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd me/resume"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "Contact"
        name = "Contact"
        url = "/contact"


# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "pop"
    name       = "pop"
    url        = "/pop"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/"

  [[params.social]]
    name = "email"
    url  = "mailto:nobody@example.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/"

